---
- hosts: app
  become: true
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
      when: ansible_distribution == "CentOS"
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
      when: ansible_distribution == "CentOS"
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
      when: ansible_distribution == "CentOS"
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_distribution == "CentOS"
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      when: ansible_distribution == "CentOS"
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"